// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyOns5_sMhpIbbfsubTPV-DV_HRYwOGH0',
    appId: '1:141001897229:web:9fc8ca4e2316ae97da6c44',
    messagingSenderId: '141001897229',
    projectId: 'authlog-69d1b',
    authDomain: 'authlog-69d1b.firebaseapp.com',
    storageBucket: 'authlog-69d1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRimKkFcnz9279j0Ilwz03wborgaflX38',
    appId: '1:141001897229:android:9da0da04d6d72ef7da6c44',
    messagingSenderId: '141001897229',
    projectId: 'authlog-69d1b',
    storageBucket: 'authlog-69d1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT8Xm-6f6i9YH80hUpvqZwa6UoD_TAnMo',
    appId: '1:141001897229:ios:094269fbb8aebb94da6c44',
    messagingSenderId: '141001897229',
    projectId: 'authlog-69d1b',
    storageBucket: 'authlog-69d1b.appspot.com',
    iosBundleId: 'com.example.c120397',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT8Xm-6f6i9YH80hUpvqZwa6UoD_TAnMo',
    appId: '1:141001897229:ios:316c7878df17b84cda6c44',
    messagingSenderId: '141001897229',
    projectId: 'authlog-69d1b',
    storageBucket: 'authlog-69d1b.appspot.com',
    iosBundleId: 'com.example.c120397.RunnerTests',
  );
}
